#!/bin/bash
#SBATCH --job-name='1027c207-6354-4a2b-ba28-661c7cae7563'
#SBATCH --output='/home/juruch/Internship-Sherbrooke/PR-AUM/AUM-mlr3torche-conv/logs/job1a76c47f1177abd4fa015f5dbcd7f642.log_%a'
#SBATCH --error='/home/juruch/Internship-Sherbrooke/PR-AUM/AUM-mlr3torche-conv/logs/job1a76c47f1177abd4fa015f5dbcd7f642.log_%a'
#SBATCH --time=120
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=6000


#SBATCH --array=1-6
export DEBUGME=
module load r/4.3.1
Rscript -e 'batchtools::doJobCollection("/home/juruch/Internship-Sherbrooke/PR-AUM/AUM-mlr3torche-conv/jobs/job1a76c47f1177abd4fa015f5dbcd7f642.rds")'
